version: '3.3'

services:
  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: my-frontend-app-container
    ports:
      - '3001:3001'
    restart: always
